This model train on account who add more products on June 2015. Use only demographic features.

In [1]:
import numpy as np
import pandas as pd

In [2]:
train_cols = ['fecha_dato',
 'ncodpers','ind_empleado','pais_residencia','sexo','age','fecha_alta','ind_nuevo','antiguedad','indrel',
 'indrel_1mes','tiprel_1mes','indresi','indext','conyuemp','canal_entrada','indfall',
 'tipodom','cod_prov','ind_actividad_cliente','renta','segmento',
 'ind_ahor_fin_ult1','ind_aval_fin_ult1','ind_cco_fin_ult1','ind_cder_fin_ult1','ind_cno_fin_ult1','ind_ctju_fin_ult1',
 'ind_ctma_fin_ult1','ind_ctop_fin_ult1','ind_ctpp_fin_ult1','ind_deco_fin_ult1','ind_deme_fin_ult1',
 'ind_dela_fin_ult1','ind_ecue_fin_ult1','ind_fond_fin_ult1','ind_hip_fin_ult1','ind_plan_fin_ult1',
 'ind_pres_fin_ult1','ind_reca_fin_ult1','ind_tjcr_fin_ult1','ind_valo_fin_ult1','ind_viv_fin_ult1','ind_nomina_ult1',
 'ind_nom_pens_ult1','ind_recibo_ult1']

notuse = ["ult_fec_cli_1t","nomprov"]

product_col = [
 'ind_ahor_fin_ult1','ind_aval_fin_ult1','ind_cco_fin_ult1','ind_cder_fin_ult1','ind_cno_fin_ult1','ind_ctju_fin_ult1',
 'ind_ctma_fin_ult1','ind_ctop_fin_ult1','ind_ctpp_fin_ult1','ind_deco_fin_ult1','ind_deme_fin_ult1',
 'ind_dela_fin_ult1','ind_ecue_fin_ult1','ind_fond_fin_ult1','ind_hip_fin_ult1','ind_plan_fin_ult1',
 'ind_pres_fin_ult1','ind_reca_fin_ult1','ind_tjcr_fin_ult1','ind_valo_fin_ult1','ind_viv_fin_ult1','ind_nomina_ult1',
 'ind_nom_pens_ult1','ind_recibo_ult1']

In [3]:
df_train = pd.read_csv('input/train_ver2.csv',usecols=train_cols)

/Users/rkcosmos/anaconda/lib/python3.5/site-packages/IPython/core/interactiveshell.py:2717: DtypeWarning: Columns (5,8,11,15) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [6]:
df_recent = df_train[['ncodpers'] + product_col]
df_recent = df_recent.drop_duplicates(['ncodpers'], keep='last')

df_recent.to_csv('cleaned_data/df_recent.csv')

In [8]:
pd.set_option('display.max_columns', None)

In [9]:
df_train_may = df_train[df_train['fecha_dato']=='2015-05-28']
df_train_june = df_train[df_train['fecha_dato']=='2015-06-28']

df_train.drop('fecha_dato', axis=1, inplace=True)

In [10]:
dfm = pd.merge(df_train_june,df_train_may, how='inner', on=['ncodpers'], suffixes=('', '_prev'))

In [11]:
prevcols = [col for col in dfm.columns if '_ult1_prev' in col]
currcols = [col for col in dfm.columns if '_ult1' in col and '_ult1_prev' not in col]

In [12]:
def test(x):
    for col in currcols:
        if x[col+'_prev'] < x[col]:
            return True
        else:
            pass
    return False

dfm['test'] = dfm.apply(test, axis=1)

In [13]:
dfm = dfm[dfm['test']==True]
dfm.drop(prevcols, axis=1, inplace=True)

In [14]:
prevcols2 = [col for col in dfm.columns if '_prev' in col]
dfm.drop(prevcols2, axis=1, inplace=True)

df_train1 = dfm

In [15]:
df_train1.drop('test', axis=1, inplace=True)

In [16]:
df_train1.head()

,fecha_dato,ncodpers,ind_empleado,pais_residencia,sexo,age,fecha_alta,ind_nuevo,antiguedad,indrel,indrel_1mes,tiprel_1mes,indresi,indext,conyuemp,canal_entrada,indfall,tipodom,cod_prov,ind_actividad_cliente,renta,segmento,ind_ahor_fin_ult1,ind_aval_fin_ult1,ind_cco_fin_ult1,ind_cder_fin_ult1,ind_cno_fin_ult1,ind_ctju_fin_ult1,ind_ctma_fin_ult1,ind_ctop_fin_ult1,ind_ctpp_fin_ult1,ind_deco_fin_ult1,ind_deme_fin_ult1,ind_dela_fin_ult1,ind_ecue_fin_ult1,ind_fond_fin_ult1,ind_hip_fin_ult1,ind_plan_fin_ult1,ind_pres_fin_ult1,ind_reca_fin_ult1,ind_tjcr_fin_ult1,ind_valo_fin_ult1,ind_viv_fin_ult1,ind_nomina_ult1,ind_nom_pens_ult1,ind_recibo_ult1
160,2015-06-28,1063273,N,ES,V,37,2012-09-19,0.0,34,1.0,1,A,S,N,NaN,KFC,N,1.0,28.0,1.0,107894.52,02 - PARTICULARES,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1.0,1.0,1
169,2015-06-28,1063250,N,ES,H,40,2012-09-19,0.0,34,1.0,1,A,S,N,NaN,KFC,N,1.0,28.0,1.0,93847.89,02 - PARTICULARES,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0.0,0.0,1
177,2015-06-28,1063226,N,ES,V,46,2012-09-19,0.0,34,1.0,1,I,S,N,NaN,KFC,N,1.0,29.0,0.0,54195.30,02 - PARTICULARES,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0.0,0.0,1
187,2015-06-28,1063241,N,ES,H,41,2012-09-19,0.0,34,1.0,1,A,S,N,NaN,KFC,N,1.0,32.0,1.0,108502.56,02 - PARTICULARES,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0.0,0.0,0
191,2015-06-28,1063292,N,ES,V,65,2012-09-19,0.0,34,1.0,1,A,S,N,NaN,KFC,N,1.0,29.0,1.0,NaN,02 - PARTICULARES,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0.0,0.0,1

In [17]:
df_train1.to_csv('cleaned_data/juneExtra.csv')